# Generated by Django 5.2.4 on 2025-07-22 18:46

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_alter_customuser_managers_alter_customuser_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to=documents.models.user_directory_path),
        ),
    ]
